# Copyright (c) 2020 Luca Cappa
# Copyright (c) 2021 Edward Rudd
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT

name: 'action-get-ninja'
description: 'Installs (and caches) ninja onto GitHub runners.'
author: 'Edward Rudd https://github.com/urkle'
inputs:
  version:
    description: 'Version of ninja-build to install'
    default: '1.10.2'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'terminal'  
  color: 'green'
